

* About this FAQ

Uploaded to GameFaqs 2015-04-05 by sebffvr

You can send patches for this guide on Github:
https://github.com/sebffvr/faq-moviewood

This FAQ is largely complete though I am still adding some hints. It
is based on the iOS/iPad version of this game.

* About Moviewood

Moviewood is a hidden object / social game that is not particularly
brilliant or complicated, but which I have found annoyingly
compulsive. It has an online/social component and I have noticed
players miss some fundamental aspects of that interaction, hence this
FAQ.

Gameplay: By doing hidden object scenes you get XP and money that
allow you to build up your movie lot and acquire and upgrade more
scenes.

Although you can buy in-game gold and cash with real money, it is
possible to play the game without spending real money. 

* Important Tips:

tl;dr: 

- You need to REQUEST props by clicking on the "head" (bottom right)
  part of the icon of a prop required for upgrade and then making a
  server connection by visiting a friend. Friends can NOT give you
  props if you don't request them. When someone gifts you a prop, you
  have to go click on your scene's upgrade pop-up for the same or a
  different prop again. See Giving and Receiving Props.

- Never spend gold on anything temporary like speeding up the clock -
  it's rare and can only be obtained for real money in sufficient
  quantities. Save it for buying Sets you cannot acquire any other way.

- Never gift the Baloon prop until you have upgraded the scenes that
  need them - they are extremely rare.

- It is entirely possible to play the game without spending real
  money. If you really want to spend real money to support the
  developers, do it on the Lottery. The "buy gold" and "buy money"
  options are NOT a good deal.

- Keep only three scenes you like on the lot so you can film scenes
  with them over and over racking full-chain bonuses.

- If you read one section in this FAQ, read the 'Friends' section. 


* Game Mechanics

** Scenes

To gain XP and cash, you have to "shoot movies". Each movie consists
of three hidden object tableaux. Up to 13 hidden objects are in each
scene. Getting all 13 rapidly gives you extra points. 

Scenes are built using Movie Coins - a new Scene opens roughly every
other level.

There are a fixed number of objects to be found in each scene at fixed
locations; however some of them can be in one of two
locations in any particular scene.

Additional points can be earned when there is a handicap in the
scene. These include

- Dark (move the lit area around to find objects)
- Fog
- Water
- Bubbles

Also, sometimes scenes appear in their mirror image (no extra points
are awarded for that). Scenes can be updated with Props (see the Props
FAQ) after level 4.

See the Scenes and Sets FAQ for a list of Scenes.

** Sets

Sets drop Movie Coins in fixed time intervals and Props (seemingly
randomly but a given set can only drop certain props - see the Props
section).

Sets are built using game cash. A new set opens every other level or
so, usually alternating with scene. You can sell Sets but you
shouldn't - you only recoup a tiny fraction of their cost, and they
come in useful when you need multiples of a specific set for a task or
for a prop drop.

See the Scenes and Sets FAQ for a list of Sets.

** Tasks

Tasks are missions assigned to you by the game. Completing tasks earns
XP and Cash and occasionally other rewards such as scripts, actors or
rare props. 

Once a day, two time-critical tasks are given - a short one (4 hours)
and a long one (8 hours). These are the game's main source of XP
growth, but never spend gold in order to complete them. They are
usually do-able without, and if you can't do them never mind, there
will be two more the next day.

The tasks apper in the beginning of the "game day". Check the tasks
before you collect movie coins, as the task may involve collecting a
certain amount of movie coins from a particular set, and that only
counts after you have opened the task. 

You do not have to accept the task. Closing the window is the same as
playing the "Let's begin" or whatever acknowledgement button.

** Props

Props are used to upgrade scenes to their maximum star value. Props
are mainly dropped by sets; they also be obtained as rewards to
Tasks occasionally. They can also be given to you by players that you
have "friended" provided you have requested them - see 'Giving and
Receiving Props'. 

For a list of available Props, the scenes they upgrade and the sets
they drop of, see the Props FAQ

** Actors

For a list of available actors see the Actors FAQ

** Hints

There are three types of Hints available in Scenes:

- Flash
- Bomb
- Chain

Flash and Chain hints can be obtained for friends (see Giving and
Receiving Hints). You start off the game with 10 Bomb Hints and that's
pretty much it.

Flash hints are best for the regular levels; occasionally there are
levels that are either in the dark or that ask you to find one of
three images rather than one of six words - chain hints work better
for those. 

There is also an infinite "Camera" hint available, however it takes
time to re-charge between uses. 

It is best to save hints for when you have to achieve a task, such as
a high score in a particular scene, rather because you are
bored/frustrated. If you can't find an item, just use a Camera hint.

** Expanding your lot

Don't use gold to expand your lot. As the game progresses you can earn
enough money to buy expansions in game cash.

You can put a smaller (eg 2x2) set in a 3x3 block sized for
scenes. It's best to keep a small number of scenes (see Strategy) and
use as much of your lot of sets that drop props and movie coins.

** Decorations

Decorations seem to have no particular purpose, though some will drop
movie coins later in the game. See the Scenes and Sets FAQ for a list
of those.

** Lottery

The Lottery is, well, a lottery. It costs $1 of real money to play, so
pace yourself. About 1 times in 5 you get something wortwhile, never
anything spectacular or unobtainable by other means.

Of all the ways to spend real money in the game, it's the one that can
yield the best reward. But you know, you're still spending real money
on virtual goods, so don't be dumb about it.

* Strategy

You have a number of script slots depending on your progress in the
game. Say you have 8 script slots and you have just shot three movies
in a row. You now have to wait for new scripts to be written (one per
hour). 

If you go back to your lot and come back in three hours to
open your list of scripts, the script slots will be populated with
Scenes that are CURRENTLY BUILT ON YOUR LOT. Since most rewards come
from getting a chain of all 13 hidden objects available in a scene,
you will progress much faster if you pick three scenes you like to use
over and over until you can reliably get the 13-item chain.

You have to have at least 3 scenes on the lot at all times. If you
need to do a task (eg. "shoot 5 movies with the Brig scene") build the
Brig scene on your lot (by buying it or from your inventory) and stash
your third scene in the inventory so you still only have three scenes
on your lot. When you open the list of scripts, any unusued script
slots will be populated (provided the scripts have had time to get
written) with movies containing the Brig scene.

Prioritise upgrading the scenes you use a lot as you earn more money
for scenes that have more stars. Also, keep an eye for genre
combinations that maximise your actor star power. For example using
Jack Chine (3 stars Action, 3 stars Comedy) on a Comedy-Thriller will
only give you 3 stars from him; using him in an Action-Comedy will
result in all 6 of his stars being contributed to the movie (hence, a
much higher profit). 

Some scripts are "Premium". That means that actors are available even
if they are recharging (ie even if they are "resting" for normal
scripts). Save those for time-critical tasks. For example if you have
to shoot two movies within 4 hours with a given actor in the Drama
genre, shoot a regular script in the Drama genre (if you have one) and
then shoot a premium one straight way (if you have one). 

Another way to progress quickly is to make ample use of the Friend
features. See Friends section. Build your scenes that you are
requesting props for near the middle of your game lot - then they will
be more visible to Friends who visit you.

I find the Scenes pretty much unplayable on an iphone screen, but if
you log onto gamecenter you can play your current game on your iPhone
which will allow you to collect coins and visit friends in that boring
class/meeting you're sitting in.

* Friends

(Screen: "Heads" -> Add)

It is possible to play Moviewood without "friending" other players,
but I wouldn't recommend it - friend gifting is by far the easiest way
to obtain props, money, hints and XP. You can friend people you know
through Gamecenter or Facebook; you can also friend random Moviewood
players by inviting them (though it costs you 5 gold for 5 invites -
use judiciously).

You can also add friends by their in-game ID. For example, my in-game
ID is e3d7a1b33639 (feel free to try it - I'm trying to figure out if
there is a friend limit). If you play the game on multiple devices
(eg. iPhone and iPad) you will have different IDs and can friend your
other self.

You cannot delete a friend once added. If there is a limit in how many
you can have, I have not yet hit it (currently at ~ 50). If you pay
gold for friend invites, you can't reject any of the offered choices
and get different ones. You don't have to accept them, but not
accepting them doesn't give you that slot back. 

Aside from building rare Sets, trading gold for friend invites (if you
can't get your own) is the only other good use of gold in the game. 

** Friending & Privacy

Your real/Gamecenter identity is NOT exposed when you add friends by
'Random' or 'via ID'. The only thing a randomly added friend sees is
your Moviewood alias. 

Set your Moviewood alias to something that does not identify you but
that is reasonably distinctive. 

You cannot exhcnage messages or other content with friends. You can
only collect gift them props (from your inventory) or hints (free to
you). Hence it is a safe friending scheme for minors. 

Obviously if you are logged onto gamecenter your gamecenter ID is
visible in rankings boards etc.

** Changing your Moviewood alias. 

If you do not change your Moviewood alias from the game default of
"Player", you will be indistinguishable from every other person who
has done the same - this is NOT good, as people tend to "gift back" if
you give them something.

You can change your in-game name by clicking on the pencil icon on the
top right of the "Friends" screens. Again, you really want to do this
in order to make yourself stand out. If I get a rare prop from
'Joe123' I am going to try and give them something they need if I have
itlater; if I get one from 'Player' I have no idea which of the
several 'Player's in my friends list it came from.

You can delete the default 'Player' completely and replace it with
your own name (some people seem to append, again, this does not help
you stand out). 

You can use your native alphabet (Cyrillic etc) for your name but not
Emojis.

"Alice Star" is the default in-game friend (not a real person). She
will neither gift you nor receive gifts. 

** Visiting friends

Visiting friends results in money and XP for you, and costs nothing to
them, so do it daily. 

When you visit a friend you see money bubbles over their sets. You can
pick up to three of these money drops - you collect money *and* XP
when you do so. They then all go away until the next day. This does
NOT cost your friend either money nor XP - you get it from the game.

Over your friend's scenes you will either see nothing, or props they
have requested (see Giving and Receiving Props). If you click on the
requested prop, and you have one available, you can give that prop to
the friend. You really do give that prop away - if you have 3 Blasters
and you give one to a friend, you will have 2 left in your inventory. 

The stats at the top of the screen when you visit a friend (XP, cash)
are YOUR stats, not theirs. 

Besides money and XP, friends' sets drop blueprints, which are
required for upgrading scenes beyond level 3. 

** Giving and Receiving Props

This can be hard to realise as the game does not show you this in the
demo part nor is it mentioned in the random tips between scenes often:

You need to actively REQUEST props AND then making a server connection
by visiting a friend. Friends can NOT give you props if you don't
request them.

You can request a prop by following those steps:

1. Having a scene on your lot
2. Clicking on "Upgrade"
3. Find a prop you are still missing
4. Clicking on the "head" icon on the bottom right of the prop
   picture ("Required" is then displayed on the prop picture)
5. Making a server connection by eg. visiting a friend.

When someone gifts you a prop and you collect it, you have to go click
on your scene's upgrade pop-up to re-request the same prop (if you
need more) - collecting a gift clears your "request" flag for that
prop. 

ASK FOR PROPS ESPECIALLY EARLY IN THE GAME. The game rewards players
for giving you propos with money and XP (depending on the rarity of
the item) and it costs you nothing. Asking for reasonably common
propos will be more effective than the very rate props (everyone wants
a balloon...). 

NOTE: The game cash reward you get for GIVING a prop seems to depend
on your game level. Giving a prop with a 300 XP / 10,000 reward seems
to give you approximately 10,000*0.5*(your game level). But it will
only give you the XP listed (300) regardless. 

** Giving and Receiving Hints

You can gift each one of your friends a flash or chain hint once a
day. These gifts are free you to you (your friend gets a hint, it
costs you nothing). 

You can receive hints from your friends (they appear in
the Friends Messages tab) but you can only collect 5 per day. Any
hints you cannot collect because you have already collected 5 will
remain in the messages section for another day. 

* Daily Gift

If you check in every day with the "free gift" button (top right area
of game screen) you get, depending on where you are in the five-day
sequence:

($ == game money)

- Day 1: $25,000
- Day 2: $50,000
- Day 3: $75,000
- Day 4: $100,000
- Day 5: Random Gift

The Random Gift "roulette" is by far the most valuable, as it drops
items that are rare / hard to get otherwise. 

Random Gift seemed to go away after ~ Level 30 but then it came back
so maybe it was a glitch. You need to be connected to the network to
get the daily gift. 

* Lot helpers

There are two NPCs on the lot that offer to do things for you.

The Moviecoin collector will collect all your moviecoin drops for a
fixed number of days in exchange for gold. Don't use him - it's not a
good use of gold. 

The Scriptwriter will offer to write a script either 100,000 in game
cash or for 1 gold bar in a specific scene or genre. The 100,000 deal
is good when you are looking for a specific genre in order to complete
a task or to level up a genre. Don't take the 1 gold bar deal; after a
day the price will go back down to the 100,000 price. As you can earn
200-300K with a single movie at later levels, that is a reasonable
price.

The Scriptwriter is useful when you need a specific genre to do a
task. For getting a script with a specific scene, see the Strategy
section. 

The Scriptwriter takes 1.5 hours to produce a script in the required
scene or genre. Again, don't waste gold speeding up the clock. 

